### ISSUE TITLE
http://razor-qt.org seems not to be accessible anymore...

### ISSUE THREAD

**Issue by nnn1590** [lxqt/lxqt-about#122]
http://razor-qt.org seems not to be accessible anymore...
[http://razor-qt.org](http://razor-qt.org)はもうアクセスできないようです…

https://github.com/lxqt/lxqt-about/blob/772464aa8ba70cf199dfd0d7f32b436b7c5febcf/aboutdialog/lxqtaboutdialog.cpp#L99

[Mozilla Firefox](https://www.mozilla.org/firefox)(LANG=C) and [GNUzilla](https://www.gnu.org/software/gnuzilla/)/[GNU IceCat](https://www.gnu.org/software/icecat/):
> We can’t connect to the server at www.razor-qt.org.

[Google Chrome](https://www.google.com/chrome/):

> DNS_PROBE_FINISHED_NXDOMAIN

LXQt Version 0.12.0
LXQt About Version 0.12.0

[Ubuntu GNU/Linux 18.04 LTS \(amd64, Japanese-remix\)](https://www.ubuntulinux.jp)上の[APT](https://packages.ubuntu.com/ja/bionic/apt)で[LXQt (25)](https://packages.ubuntu.com/ja/bionic/lxqt)をインストールしました。
I installed [LXQt (25)](https://packages.ubuntu.com/bionic/lxqt) with [APT](https://packages.ubuntu.com/bionic/apt) on [Ubuntu GNU/Linux 18.04 LTS \(amd64, Japanese-remix\)](https://www.ubuntulinux.jp).
___
Translated from Japanese to English by [Google Translate](https://translate.google.com).
[Google 翻訳](https://translate.google.co.jp)によって日本語から英語に翻訳されました。

**Comment by tsujan** [comment]
Right. I saw that after downloading `lxqt-about_0.14.1-1_amd64.deb`.
